// Generated by CoffeeScript 1.6.1
(function() {

  define(["d3"], function(d3) {
    'use strict';
    var graph;
    graph = function() {
      var height, margin, width, x, xAxis, y, yAxis;
      margin = {
        top: 20,
        right: 20,
        bottom: 30,
        left: 40
      };
      width = 960 - margin.left - margin.right;
      height = 500 - margin.top - margin.bottom;
      x = d3.scale.ordinal().rangeRoundBands([0, width], .1);
      y = d3.scale.linear().range([height, 0]);
      xAxis = d3.svg.axis().scale(x).orient("bottom");
      yAxis = d3.svg.axis().scale(y).orient("left").ticks(10, "%");
      graph = function(selection) {
        selection.selectAll(".bar").data(function(d) {
          return d;
        }).enter().append("rect").attr("class", " bar").attr("x", function(d) {
          return x(d.letter);
        }).attr("y", function(d) {
          return y(d.frequency);
        }).attr("width", x.rangeBand()).attr("height", function(d) {
          return height - y(d.frequency);
        });
        selection.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis);
        selection.append("g").attr("class", "y axis").call(yAxis).append("text").attr("transform", "rotate(-90)").attr("y", 6).attr("dy", ".71em").style("text-anchor", "end").text("Frequency");
        return this;
      };
      graph.width = function(value) {
        if (!arguments.length) {
          return width;
        }
        width = value;
        return graph;
      };
      graph.height = function(value) {
        if (!arguments.length) {
          return height;
        }
        height = value;
        return graph;
      };
      return graph;
    };
    return graph;
  });

}).call(this);
