// Generated by CoffeeScript 1.6.1
(function() {
  var App;

  define(["backbone", "d3"], function(Backbone, d3) {
    return "use strict";
  });

  App = _.extend({
    config: require.appConfig,
    initialize: function() {
      var _this = this;
      require(["views/main", "views/frequency"], function(MainView, FrequencyView) {
        var type;
        _this.view = new MainView($('#main'));
        type = function(d) {
          return d.frequency = +d.frequency;
        };
        d3.tsv("app/data/eng.tsv", type, function(error, data) {
          var frequencyView;
          frequencyView = new FrequencyView({
            data: data
          });
          return this.view.render(frequencyView.render(), '#container');
        });
        return _this;
      });
      return this;
    }
  });

  window.App = App;

}).call(this);
