// Generated by CoffeeScript 1.9.1
(function() {
  define(["backbone"], function(Backbone) {
    "use strict";
    var App;
    App = _.extend({
      config: require.appConfig,
      initialize: function() {
        require(["views/main", "views/index", "views/myself", "views/projects", "views/contact", "views/tree", "views/menu"], (function(_this) {
          return function(MainView, IndexView, MyselfView, ProjectsView, ContactView, TreeView, MenuView) {
            _this.view = new MainView($('#main'));
            _this.view.render((new IndexView()).render(), '#container');
            _this.view.render((new MyselfView()).render(), '#container');
            _this.view.render((new ProjectsView()).render(), '#container');
            _this.view.render((new ContactView()).render(), '#container');
            _this.view.render((new TreeView()).render(), '#container');
            _this.view.render((new MenuView()).render().initScroll(), '#sidebar');
            return _this;
          };
        })(this));
        return this;
      }
    });
    return window.App = App;
  });

}).call(this);
