// Generated by CoffeeScript 1.6.1
(function() {

  define(['backbone', 'graphs/frequency', 'text!templates/frequency.tpl', 'd3'], function(Backbone, frequencyGraph, tpl, d3) {
    return Backbone.View.extend({
      tagName: 'section',
      className: 'section',
      id: 'visualization',
      template: _.template(tpl),
      initialze: function() {
        this.graph = frequencyGraph().width(200).height(200);
        return this.data = this.options.data || [];
      },
      render: function() {
        this.$el.html(this.template);
        this.g = d3.select("#graph").append("svg").append("g").attr("transform", "translate(0, 0)").data(this.data).call(this.graph);
        return this;
      }
    });
  });

}).call(this);
