// Generated by CoffeeScript 1.6.1
(function() {

  define(['backbone', 'graphs/frequency', 'text!templates/frequency.tpl', 'd3'], function(Backbone, frequencyGraph, tpl, d3) {
    return Backbone.View.extend({
      tagName: 'section',
      className: 'section',
      id: 'visualization',
      template: _.template(tpl),
      initialize: function(options) {
        this.data = options.data || [];
        this.data = [
          {
            name: "A",
            frequency: .08167
          }, {
            name: "B",
            frequency: .01492
          }, {
            name: "C",
            frequency: .02780
          }, {
            name: "D",
            frequency: .04253
          }, {
            name: "E",
            frequency: .12702
          }
        ];
        this.graph = frequencyGraph().width(900).height(500).data(this.data);
        return this;
      },
      render: function() {
        this.$el.html(this.template);
        return this;
      },
      renderGraph: function() {
        this.g = d3.select("#graph").data(this.data).call(this.graph);
        return this;
      }
    });
  });

}).call(this);
