// Generated by CoffeeScript 1.9.1
(function() {
  define(['backbone', 'text!templates/index.tpl'], function(Backbone, tpl) {
    'use strict';
    return Backbone.View.extend({
      id: 'section1',
      tagName: 'section',
      className: 'section',
      render: function(tpl) {
        $(this.el).html(_.template(tpl));
        return this;
      }
    });
  });

}).call(this);
