// Generated by CoffeeScript 1.9.1
(function() {
  define(['backbone', 'text!templates/menu.tpl', 'waypoints'], function(Backbone, tpl) {
    'use strict';
    return Backbone.View.extend({
      initialize: function() {
        console.log("menu init");
        return this;
      },
      render: function() {
        this.$el.html(_.template(tpl));
        return this;
      },
      'initScroll': function() {
        $('section').waypoint(function(direction) {
          var sectionId;
          sectionId = parseInt($(this.element).attr('id').substr($(this.element).attr('id').length - 1));
          if (direction === 'down') {
            $('.navigation li[section="' + sectionId + '"]').addClass('active').siblings().removeClass('active');
          } else {
            $('.navigation li[section="' + (sectionId - 1) + '"]').addClass('active').siblings().removeClass('active');
          }
          return this;
        });
        return this;
      },
      toggleSidebar: function() {
        $('html').toggleClass('expanded');
        return this;
      },
      goTo: function(evt) {
        var htmlbody, section;
        section = evt.currentTarget.getAttribute('section');
        htmlbody = $('html,body');
        if (section === 1) {
          htmlbody.animate({
            scrollTop: $('#section' + section).offset().top
          }, 500, 'easeOutQuart');
        } else {
          htmlbody.animate({
            scrollTop: $('#section' + section).offset().top + 70
          }, 500, 'easeOutQuart');
        }
        return this;
      },
      events: {
        'click .btn-navbar': 'toggleSidebar',
        'click .navigation li': 'goTo'
      }
    });
  });

}).call(this);
