// Generated by CoffeeScript 1.6.1
(function() {

  define(['backbone', 'graphs/price', 'text!templates/price.tpl', 'd3'], function(Backbone, priceGraph, tpl, d3) {
    return Backbone.View.extend({
      tagName: 'section',
      className: 'section',
      id: 'visualization',
      template: _.template(tpl),
      initialze: function() {
        return this;
      },
      render: function() {
        this.$el.html(this.template);
        d3.csv("app/data/price.csv", function(data) {
          var formatDate;
          formatDate = d3.time.format("%b %Y");
          d3.select("#graph").datum(data).call(priceGraph().y(function(d) {
            return +d.price;
          }).x(function(d) {
            return formatDate.parse(d.date);
          }));
          return this;
        });
        return this;
      }
    });
  });

}).call(this);
