// Generated by CoffeeScript 1.9.1
(function() {
  define(['backbone', 'text!templates/projects.tpl'], function(Backbone, tpl) {
    'use strict';
    return Backbone.View.extend({
      'tagName': 'section',
      'className': 'section',
      'id': 'section3',
      'initialze': function() {
        console.log("project init");
        return this;
      },
      'render': function() {
        this.$el.html(_.template(tpl));
        return this;
      }
    });
  });

}).call(this);
