// Generated by CoffeeScript 1.9.1
(function() {
  define(['backbone'], function(Backbone) {
    'use strict';
    return Backbone.View.extend({
      tagName: 'section',
      className: 'section',
      constructor: function(id) {
        this.id = "section" + id;
        return this;
      },
      render: function() {
        console.log("Empty section n " + this.el.id);
        return this;
      }
    });
  });

}).call(this);
